pretrained_model_path: "runwayml/stable-diffusion-v1-5"
controlnet_model_path: "lllyasviel/sd-controlnet-canny"
data_root: "/kaggle/input/sketch-2-image-dataset/construction_sketch_dataset/construction_sketch_dataset"

train_batch_size: 4
optimizer:
  type: AdamW
  params:
    lr: 1e-4
    betas: [0.9, 0.999]
    weight_decay: 1e-2
    eps: 1e-8
lora_rank: 512
gradient_accumulation_steps: 2
max_train_steps: 10000
lr_warmup_steps: 500
max_grad_norm: 1.0

fixed_image: "/kaggle/input/val-image/whereness assignment sketch.png"
seed: 42
save_loss_threshold: 0.09888
